# Generated by Django 3.2.23 on 2023-11-26 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approved_Centres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=50)),
                ('occupation', models.CharField(choices=[('Student', 'Student'), ('Civil Servant', 'Civil Servant'), ('Business', 'Business')], max_length=50)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('residential_address', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=15)),
                ('local_government', models.CharField(max_length=50, verbose_name='Local government')),
                ('nationality', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Owner',
                'verbose_name_plural': 'Owners',
            },
        ),
        migrations.CreateModel(
            name='CarRegisteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('vehicle_category', models.CharField(choices=[('Government', 'Government'), ('Commercial', 'Commercial'), ('Private', 'Private')], max_length=15)),
                ('vehicle_sub_category', models.CharField(choices=[('Diplomatic and Foreign Mission', 'Diplomatic and Foreign Mission'), ('Federal Parastatals/Agencies/Department', 'Federal Parastatals/Agencies/Department'), ('LGA', 'LGA'), ('Military/Paramilitaries', 'Military/Paramilitaries'), ('State Ministries/Agencies/Department', 'State Ministries/Agencies/Department')], max_length=50)),
                ('old_plate_number', models.CharField(max_length=20)),
                ('vehicle_make', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Bio-Fuel', 'Bio-Fuel')], max_length=50)),
                ('year_of_manufacture', models.CharField(help_text='2000', max_length=4)),
                ('model', models.CharField(max_length=10)),
                ('engine_number', models.CharField(max_length=10)),
                ('policy_number', models.CharField(max_length=10)),
                ('vehicle_type', models.CharField(choices=[('Telsa', 'Telsa'), ('BMW', 'BMW'), ('Ferrari', 'Ferrari'), ('Honda', 'Honda'), ('Toyota', 'Toyota'), ('Audi', 'Audi'), ('Jeep', 'Jeep'), ('Mazda', 'Mazda'), ('Nissan', 'Nissan')], max_length=50, verbose_name='Vehicle Type/Group')),
                ('chassis_no', models.CharField(max_length=15, verbose_name='Chassis Number')),
                ('engine_capacity', models.CharField(choices=[('Above 3.0', 'Above 3.0'), ('Below 1.6', 'Below 1.6'), ('Between 1.6 and 2.0', 'Between 1.6 and 2.0'), ('Between 2.1 and 3.0', 'Between 2.1 and 3.0')], max_length=50)),
                ('tank_capacity', models.CharField(max_length=5)),
                ('odometer', models.CharField(max_length=15)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.owner', verbose_name='Owner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
