# Generated by Django 6.0.7 on 2026-08-02 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_auto_20231126_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carregisteration',
            old_name='old_plate_number',
            new_name='plate_number',
        ),
    ]
