# Generated by Django 6.0.7 on 2026-09-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0003_rename_old_plate_number_carregisteration_plate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carregisteration',
            name='vehicle_make',
            field=models.CharField(choices=[(100, 100), (1617, 1617), (190, 190), (420, 420), ('5 SERIES', '5 SERIES')], max_length=20),
        ),
        migrations.AlterField(
            model_name='owner',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='owner',
            name='nationality',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='owner',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
