# Generated by Django 5.2.12 on 2026-09-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0004_alter_carregisteration_vehicle_make_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carregisteration',
            name='vehicle_make',
            field=models.CharField(choices=[('100', '100'), ('1617', '1617'), ('190', '190'), ('420', '420'), ('5 SERIES', '5 SERIES')], max_length=20),
        ),
    ]
